### ISSUE TITLE
WIP / TODO Integration

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [MaxNeedsSnacks/ThermalJS#1]
This is just an issue for me to keep track of what still should / could be added to the mod. Help is greatly appreciated (in the form of pull requests), please just make sure to stick to my original naming conventions and rough code style.

**Machines:**

- [ ] Redstone Furnace
  - [ ] Pyrolysis Oven
- [ ] Pulverizer
- [ ] Sawmill
- [ ] Induction Smelter
- [ ] Phytogenic Insolator
- [ ] Compactor
  - [ ] (Support for all Compactor Modes)
- [ ] Magma Crucible
- [ ] Fractionating Still
  - [ ] Alchemical Retort
- [ ] Fluid Transposer
  - [ ] Fill
  - [ ] Empty
- [ ] Energetic Infuser
- [ ] Centrifugal Separator (!!!)
  - [ ] (Support for Mob Recipes)
- [ ] Alchemical Imbuer
- [ ] Arcane Ensorcellator
- [ ] Glacial Precipitator
- [ ] Igneous Extruder
  - [ ] Support for Sedimentary Recipes

**Devices:**

- [ ] Thermal Mediator (Coolant)
- [ ] Arboreal Extractor
- [ ] Aquatic Entangler
- [ ] Insightful Condenser
- [ ] Decotive Diffuser
- [ ] Factorizer

**Dynamos:**
- [ ] Steam Dynamo
- [ ] Magmatic Dynamo
- [ ] Compression Dynamo
- [ ] Reactant Dynamo
  - [ ] (Custom Elemental Reactions)
- [ ] Enervation Dynamo (?)
- [ ] Numismatic Dynamo
  - [ ] Lapidary Calibration
